deploy_admin_console: true

olm_version: "0.7.2"
# Override OLM image tag found in manifests Ex: "master-05a83874"
olm_image_tag_override: ""
admin_console_image: "quay.io/openshift/origin-console:latest"

# The upstream OLM repo that will be cloned and used for deployment
#olm_repo: "https://github.com/operator-framework/operator-lifecycle-manager.git"
# Using a fork so we can more easily patch in our requirements
olm_repo: "https://github.com/fusor/operator-lifecycle-manager.git"
# Could be a branch, sha, or tag
olm_repo_version: catasb
olm_repo_dest: /tmp/olm

# Template Broker and Ansible Brokers can be made available via the OLM
# catalog, creating an aditional catalog source and related OLM resources
olm_enable_osb_catalog: true
